name: test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Run All Tests in PDK Environment
        uses: TinyTapeout/tt-gds-action@ttsky25a
        with:
          mode: test
          test_command: |
            cd test
            make test-butterfly
            make test-fft-engine
            make test-memory
            make test-io
            make test-top
            ! grep failure results.xml

      - name: Test Summary
        uses: test-summary/action@v2.3
        with:
          paths: "test/results.xml"
        if: always()

      - name: upload vcd
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-vcd
          path: |
            test/results.xml
            test/top_fft/wave/